### PR TITLE
Upgrade refs to use 1.11/8.0

### PR DESCRIPTION
**Pull request by CharlyF**
Hey!
First off, thanks a lot for all the work you do, I'm using extensively the custom-metrics repo at my company and it's awesome!

As you probably know, some configs allow the creation of a requestheader CA in the extension-apiserver-authentication ConfigMap but no client CA (in EKS notably). This has been an issue for the metrics server which you fixed in 0.3.0 https://github.com/kubernetes/apiserver/commit/e59fba717fdb3c4dafdbe6c5af9653313c288119

But the commit ref in the lock for the apiserver here is too old, so the [upstream fix](https://github.com/kubernetes/kubernetes/pull/66394) is not embedded.

I don't believe that this contribution will be merged, but I wanted to bring it up to your attention.
I have been using this code on my external metrics server successfully - If you find time to upgrade the glide here, that would be fantastic. Hopefully this PR might help!

Thanks again,
Charly

### CODE REVIEW

**Comment by DirectXMan12** [comment]
thanks for the PR!  I'm in the process of updating some other repos with similar changes right now, so I want to double-check that the dependency versions listed here don't cause vendoring issues, but it they don't, I'll merge this.

**Comment by DirectXMan12** [comment]
Works for me.  Hmm... looks like travis is trying to run glide, which isn't in Travis.  Can you make sure glide.lock and vendor are up-to-date.

**Comment by CharlyF** [comment]
> Works for me. Hmm... looks like travis is trying to run glide, which isn't in Travis. Can you make sure glide.lock and vendor are up-to-date?

The hash is pretty consistent but I've tried a few things, locally it works fine - I wonder if it could be the cache on Travis's side ?

**Comment by mfpierre** [comment]
@DirectXMan12 I think there's an issue with the current `Makefile` 

`vendor: glide.lock` will run `glide install` is the `glide.lock` has been modified after the `vendor` directory, the thing is you can't really control this date with `git`. (because they are not `PHONY` targets)

State when I clone the repo:
```
-rw-r--r--   1 pierremargueritte  staff  16583 Oct  4 14:59 glide.lock
drwxr-xr-x   8 pierremargueritte  staff    256 Oct  4 14:54 vendor
```

so `make vendor` will run `glide install`

but if I do `touch vendor` then `make: "vendor" is up to date.`

We have several solutions:
* add `glide` back to travis
* remove `vendor`as a prerequisite for `test`, and maybe add another target for this

Not sure what strategy do you want for this repo?

**Comment by DirectXMan12** [comment]
I'd remove vendor as a dependency for everything, it gets weird otherwise.

**Comment by CharlyF** [comment]
Let me know if that looks better @DirectXMan12. Thanks for your review 🙇

**Comment by astefanutti** [comment]
@CharlyF I only noticed this PR after I created #34. Agreed both PRs can be merged sequentially so we're on the safe side.

**Comment by CharlyF** [comment]
@DirectXMan12, sorry for the direct ping - Any chance you can let us know if this is good to go ?

**Comment by DirectXMan12** [comment]
hey, sorry about the delay -- I was out of the office for the past few weeks.  I'll try to review this this week, and hopefully get it merged.

**Pull request merged**
