### PR TITLE
upgrade to kubernetes 1.15

### PR DESCRIPTION
**Pull request by CharlyF**
Using the operator SDK 0.10.0 and other recent libraries (controller-runtime, controller-tools) I would need to have a more recent version of kubernetes in the `custom-metrics-apiserver` for my CRD.

Thanks!

### CODE REVIEW

**Comment by CharlyF** [comment]
Thoughts on this @astefanutti ? (I know you are not a maintainer, but we had a similar conversation about a year ago to bump the dependencies 🙂 ).
/assign kawych

**Comment by astefanutti** [comment]
@CharlyF yes, it makes sense to keep current w.r.t. k8s version.

**Comment by kawych** [comment]
@CharlyF Could you please split this PR so that the changes in vendor/ directory and glide.* files are in separate commits for easier review?

**Pull request merged**
