### PR TITLE
Upgrade to Kubernetes 1.12

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by DirectXMan12** [comment]
This looks pretty reasonable.  Just to be double certain, I seem to recall some weird issue when rebasing on 1.12.  Everything seems to run fine with this code on your end?

**Comment by astefanutti** [comment]
@DirectXMan12 I've tested these changes with the test adapter and it works fine.

**Comment by DirectXMan12** [comment]
oh, shoot, I've no idea why I closed this PR.  Sorry about that.  If you can rebase we can get this merged.

**Comment by astefanutti** [comment]
No worries. I've just rebased it and tested it works ok with the test adapter.

**Pull request merged**
