### PR TITLE
converts dependency toolchain to use modules

### PR DESCRIPTION
**Pull request by brendanjryan**
Converts this repository to use `go modules` as its primary dependency management toolchain. For backwards compatibility - I left the old `glide` based toolchain intact.

### CODE REVIEW

**Comment by brendanjryan** [comment]
This should be ready for review!

/assign @kawych

**Comment by astefanutti** [comment]
@brendanjryan there may be a couple of doc changes that you could pick from #54.

**Comment by brendanjryan** [comment]
ah I didn't notice you had a patch open implementing almost the same thing @astefanutti ! 

Is yours ready to merge in? I would gladly like to abandon this patch if so

**Comment by astefanutti** [comment]
@brendanjryan it's likely yours is more up-to-date. I'm happy to close mine in favour of yours.

**Comment by brendanjryan** [comment]
@astefanutti sounds good! Let me copy over some of the README changes and i'll ping you and the core maintainers when ready!

**Comment by brendanjryan** [comment]
Ping @kawych -- is this repo under active development?

**Comment by fxposter** [comment]
Hello. I just wonder, why go.mod was included with "github.com/brendanjryan/custom-metrics-apiserver" module name instead of "github.com/kubernetes-incubator/custom-metrics-apiserver"?

**Comment by brendanjryan** [comment]
@fxposter this was a mistake and should be fixed in https://github.com/kubernetes-incubator/custom-metrics-apiserver/pull/58

**Pull request merged**
