### PR TITLE
Fix minor typo in pkg/provider/interfaces.go

### PR DESCRIPTION
**Pull request by fj**

### CODE REVIEW

**Comment by fj** [comment]
Hello! I've signed the CLA now.

**Comment by fj** [comment]
/remove-lifecycle stale

also /cc'ing @DirectXMan12 as per the robot suggestion

**Comment by DirectXMan12** [comment]
FYI: I'm no longer working on metrics stuff as much -- ping @s-urbaniak :-)

**Comment by kylee12** [comment]
Never signed up for this my husband probably did Raymond Zimmerman but he passed away may 24 2017

**Pull request merged**
